services:
  - type: web
    name: soundverse-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: soundverse-db
          property: connectionString
    plan: free

databases:
  - name: soundverse-db
    plan: free